<?php include('header.phtml'); ?>

<div class="container-titulo"><h2>Categorias</h2></div>
<div class="container-categoria">
<table class="table">
    <thead>
      <tr>
      <th scope='col'>Categoria</th>
      <th scope='col'>Producto</th>
      <th scope='col'>Informacion</th>
      <th scope='col'>Detalles</th>
      <th scope='col'>Borrar</th>
      <th scope='col'>Editar</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($categorias as $categoria ){ ?>
      <tr>
      <td><p><?= $categoria->id_categoria ?></p></td>
      <td><p><?= $categoria->tipo_prenda ?></p></td>
      <td><p><?= $categoria->detalle ?></p></td>
      <td><a href='detalleCategoria/<?= $categoria->id_categoria ?>' type='button'>Detalles</a></td>
      <?php // if(authHelper::verify()){ ?>
      <td><a href='deleteCategoria/<?= $categoria->id_categoria ?>' type='button'>Borrar</a></td> 
      <td><a href='editCategoria/<?= $categoria->id_categoria ?>' type='button'>Editar</a></td> 
      <?php // } ?>
      <?php } ?>
      </tr>

    </tbody>
  </table>
</div>

    <?php include('templates/formAddCategoria.phtml'); ?>
