<?php include('header.phtml'); ?>
<table class="table">
    <thead>
      <tr>
      <th scope='col'>Categoria</th>
      <th scope='col'>Producto</th>
      <th scope='col'>Informacion</th>
      <th scope='col'>Detalles</th>
      <th scope='col'>Borrar</th>
      <th scope='col'>Editar</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($categorias as $categoria ){ ?>
      <tr>
      <td><?= $categoria->id_categoria ?></td>
      <td><?= $categoria->tipo_prenda ?></td>
      <td><?= $categoria->detalle ?></td>
      <td><a href='detalleCategoria/<?= $categoria->id_categoria ?>' type='button'>Detalles</a></td>
      <td><a href='deleteCategoria/<?= $categoria->id_categoria ?>' type='button'>Borrar</a></td> 
      <td><a href='editCategoria/<?= $categoria->id_categoria ?>' type='button'>Editar</a></td> 

      <?php } ?>
      </tr>

    </tbody>
  </table>

    <?php include('templates/formAddCategoria.phtml'); ?>
