<?php require('header.phtml') ?>
<table class="table">
    <thead>
      <tr>
        <th scope='col'>ID_categoria</th>
        <th scope='col'>Categoria</th>
        <th scope='col'>Informacion</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($categorias as $categoria ): ?>
      <tr>
      <td><?= $categoria->id_categoria?></td>
      <td><?= $categoria->tipo_prenda?></td>
      <td><?= $categoria->detalle?></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>