<?php require('header.phtml') ?>
<div class="container-categoria-detalles">
<table class="table">
    <thead>
      <tr>
        <th scope='col'>ID_categoria</th>
        <th scope='col'>Categoria</th>
        <th scope='col'>Informacion</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach($categorias as $categoria ): ?>
      <tr>
      <td><p><?= $categoria->id_categoria?></p></td>
      <td><p><?= $categoria->tipo_prenda?></p></td>
      <td><p><?= $categoria->detalle?></p></td>
      </tr>
      <?php endforeach; ?>
    </tbody>
  </table>
</div>