<?php include 'header.phtml'; ?>
<div class="container-producto-detalles">
<table class="table">
    <thead>
      <tr>
        <th scope='col'>Categoria</th>
        <th scope='col'>Producto</th>
        <th scope='col'>Tipo</th>
        <th scope='col'>Talle</th>
        <th scope='col'>Precio</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($prods as $producto) { ?>
      <tr>
      <td><p><?= $producto->id_categoria ?></p></td>
      <td><p><?= $producto->id_producto?></p></td>
      <td><p><?= $producto->tipo ?></p></td>
      <td><p><?= $producto->talle ?></p></td>
      <td><p><span>$</span><?= $producto->precio ?></p></td>
      </tr>
      <?php } ?>
    </tbody>
  </table>
</div>