<?php include 'header.phtml'; ?>
<table class="table">
    <thead>
      <tr>
        <th scope='col'>Categoria</th>
        <th scope='col'>Producto</th>
        <th scope='col'>Tipo</th>
        <th scope='col'>Talle</th>
        <th scope='col'>Precio</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($productById as $product) { ?>
      <tr>
      <td><?= $product->id_categoria_fk ?></td>
      <td><?php $product->id_producto?></td>
      <td><?php $product->tipo ?></td>
      <td><?php $product->talle ?></td>
      <td><span>$</span><?php $product->precio ?></td>
      </tr>
      <?php } ?>
    </tbody>
  </table>