<footer class="footer">
    <div class="container">

      <div class="zona-info"> 
        <div class="con">
          <h4>Contacto</h4>
          <p>Celular: +2494519078</p>
          <p>Email: SectaCopera@products.com</p>
          <p>Dirección: Espora 1074, Tandil</p>
        </div>

        <div class="con">
          <h4>Enlaces Rápidos</h4>
          <ul>
            <li><a href="#">Inicio</a></li>
            <li><a href="#">Nosotros</a></li>
            <li><a href="#">Contacto</a></li>
          </ul>
        </div>

        <div class="con">
          <h4>Síguenos</h4>
          <ul>
            <li><a href="#">Facebook</a></li>
            <li><a href="https://www.instagram.com/niico_gomezz__/">Instagram</a></li>
            <li><a href="#">Twitter</a></li>
          </ul>
        </div>
      </div>

      <div class="zona-copy">
        <div>
          <hr>
          <p>&copy; 2024 Secta Copera - Todos los derechos reservados</p>
        </div>
      </div>

    </div>
  </footer>