<?php require_once 'templates/header.phtml' ?>

<div class="container-edit-producto">
<form class="form" action="updateProduct/<?= $prods->id_producto; ?>" method="post" required>
    <label for="tipo">TIPO:</label>
    <input type="text" class="form-control" id="tipo" name="tipo" value="<?= $prods->tipo; ?>" required>

    <label class="form-label" for="talle">TALLE:</label>
    <input type="text" class="form-control" id="talle" name="talle" value="<?= $prods->talle; ?>" required>


    <label for="precio">PRECIO:</label>
    <input type="number" class="form-control" id="precio" name="precio" value="<?= $prods->precio; ?>" required>

    <button class="btn btn-success" type="submit">Actualizar producto</button>
</form>
</div>
