<div class="container-add-producto">
    
<form class="formulario" action="add" method="POST">
    <div>
        <label class="form-label">NUMERO CATEGORIA</label>
        <select name="id_categoria" class="form-control"> 
            <?php foreach ($productos as $producto) { ?>
            <option value='<?= $producto->id_categoria?>'><?= $producto->id_categoria?> - <?= $producto->tipo?>
        </option>
            <?php } ?>
        </select>
    </div>
    
    <div>
        <label class="form-label">TIPO</label>
        <input type="text" name="tipo" placeholder="Ingrese un tipo de prenda" class="form-control" required>
    </div>
    <div>
        <label class="form-label">TALLE</label>
        <input type="text" name="talle" placeholder="Ingrese un talle" class="form-control" required>
    </div>
    <div>
        <label class="form-label">PRECIO</label>
        <input type="text" name="precio" placeholder="Ingrese un precio" class="form-control" required>
    </div>
        <button type="submit" class="btn-form-login">Agregar Producto</button>
    </form>

</div>