<form class="formulario" action="addCategoria" method="POST">
    <div>
        <label class="form-label">NUMERO CATEGORIA</label>
        <input type="text" name="id_categoria" placeholder="Ingrese un num de cat inexistente" class="form-control" required>
    </div>
      <div>
        <label class="form-label">TIPO DE PRENDA</label>
        <input type="text" name="tipo_prenda" placeholder="Ingrese la categoria" class="form-control" required>
    </div>
    <div>
        <label class="form-label">DETALLE</label>
        <input type="text" name="detalle" placeholder="Ingrese detalles de la categoria" class="form-control" required>
    </div>
        <button type="submit" class="btn-form-login">Agregar Categoria</button>
    </form>