<!DOCTYPE html>
<html lang="en">
<head>
    <base href="{BASE_URL}">
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://fonts.googleapis.com/css2?family=Heebo&family=Nunito:wght@300&family=Poppins:wght@300&family=Roboto:wght@300&family=Tilt+Neon&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="styles/style.css">
    <title>Secta Copera</title>
</head>
<body>
    <header>
    <div class="fondo">
        <nav class="navbar">
            <div class="logo">Secta Copera</div>
            <div class="nav">
            <ul class="nav-list">
                <li><a href="home">Home</a></li>
                <li><a href="producto">Producto</a></li>
                <li class="dropdown">
                    <a href="categoria">Categoria</a>
                </li>
            </ul>
            </div>
        </nav>
    </header>