<?php require('header.phtml') ?>

<div class="container-home">
    <section class="hero">
        <div class="hero-content">
            <h1>Secta Copera</h1>
            <p>Encuentra las mejores indumentarias de los equipos mas ganadores internacionalmente del pais</p>
            <div class="container">
            <button class="shop-btn">Comprar Ahora</button>
            </div>
        </div>
    </section>

    <div class="container-productos">
    <section class="productos">
        <div class="titulo">
        <h2>Productos Destacados</h2>
        </div>
        <div class="prods">
        <div class="producto">
            <a href="producto"><img src="imgs/indumentaria-independiente.png" alt="Producto 1"></a>
        </div>
        <div class="producto">
            <a href="producto"><img src="imgs/indumentaria-boca.jpg" alt="Producto 2"></a>
        </div>
        </div>
    </section>
    </div>


</div>

<?php require('footer.phtml') ?>

</body>
</html>