<?php require('header.phtml') ?>
<div class="container-home">
    <section class="hero">
        <div class="hero-content">
            <h1>Secta Copera</h1>
            <p>Encuentra las mejores indumentarias de los equipos mas ganadores internacionalmente del pais</p>
            <div class="container">
            <button class="shop-btn">Comprar Ahora</button>
            </div>
        </div>
    </section>

    <section class="featured-products">
        <h2>Productos Destacados</h2>
        <div class="product">
            <img src="../imgs/indumentaria-independiente.webp" alt="Producto 1">
            <h3>Independiente</h3>
        </div>
        <div class="product">
            <img src="../imgs/indumentaria-boca.jpg" alt="Producto 2">
            <h3>Boca</h3>
        </div>
    </section>

</div>
</div>

<?php require('footer.phtml') ?>

</body>
</html>