<?php require('header.phtml') ?>

<div class="container-login">
<div class="formulario">
    <form action="validate" method="POST" class="sub-form">
        <div class="upper-form">
            <h2>Login Form</h2>
            <label for="username">Username</label><br>
            <input type="text" id="usr" name="usr"><br>
            <label for="password">Password</label><br>
            <input type="password" id="con" name="con"><br>
            <div class="btn-login">
                <button type="submit" class="btn-form-login">Login</button>
            </div>
            <div class="container-imgs">
            <img src="imgs/escudo-independiente.png" alt="">
            <img src="imgs/escudo-boca.png" alt="">
            </div>
        </div>
        <div class="button-form"></div>
    </form>

</div>
</div>

<?php if ($error): ?>
            <div class="container-error">
            <div class="error">
                <?= $error ?>
            </div>
            </div>
<?php endif ?>