<?php require('header.phtml') ?>
<table class="tableProduct">
    <thead>
      <tr>
      <th class='col'>#</th>
      <th scope='col'>Categoria</th>
      <th scope='col'>Producto</th>
      <th scope='col'>Talle</th>
      <th scope='col'>Precio</th>
      <th scope='col'></th>
      <th scope='col'></th>
      <th scope='col'></th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($productos as $producto) : ?>
      <tr>
        <td><?php $producto->id_categoria?></td>
        <td><?php $producto->id_producto?></td>
        <td><?php $producto->tipo?></td>
        <td><?php $producto->talle?></td>
      <td><span>$</span><?php $producto->precio?> </td>
      <td><a href='detalle/{$product->id_producto}' type='button'>Detalles</a></td>
      
      <?php //if(verify()){ ?>
      <td><a href='delete/{$product->id_producto}' type='button'>Borrar</a></td> 
      <td><a href='edit/{$product->id_producto}' type='button'>Editar</a></td> 
      <?php //} ?>
      
      </tr>
      <?php endforeach; ?>
    </tbody>
</table>

<?php require('formAddProducto.phtml') ?>