<?php include('templates/header.phtml'); ?>
<div class="container-producto">
<table class="table"> 
    <thead>
      <tr>
      <th class='col'>#</th>
      <th scope='col'>Categoria</th>
      <th scope='col'>Producto</th>
      <th scope='col'>Talle</th>
      <th scope='col'>Precio</th>
      <th scope='col'>Detalles</th>
      <th scope='col'>Borrar</th>
      <th scope='col'>Editar</th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($prods as $prod ) : ?>
      <tr>
        <td><p><?= $prod -> id_categoria ?></p></td>
        <td><p><?= $prod -> id_producto ?></p></td>
        <td><p><?= $prod -> tipo ?></p></td>
        <td><p><?= $prod -> talle ?></p></td>
        <td><span>$</span><p><?= $prod -> precio ?></p></td>
        <td><a href='detalle/<?= $prod->id_producto ?>' type='button'>Detalles</a></td>
        <td><a href='delete/<?= $prod->id_producto ?>' type='button'>Borrar</a></td> 
        <td><a href='formActualizarProdcuto/<?= $prod->id_producto ?>' type='button'>Editar</a></td> 
      </tr>
    <?php endforeach; ?>
    </tbody>
</table>
</div>

<?php require('formAddProducto.phtml') ?>