<?php include('templates/header.phtml'); ?>
<table class="tableProduct"> 
    <thead>
      <tr>
      <th class='col'>#</th>
      <th scope='col'>Categoria</th>
      <th scope='col'>Producto</th>
      <th scope='col'>Talle</th>
      <th scope='col'>Precio</th>
      <th scope='col'></th>
      <th scope='col'></th>
      <th scope='col'></th>
      </tr>
    </thead>
    <tbody>
    <?php foreach ($prods as $prod ) : ?>
      <tr>
        <td><?= $prod -> id_categoria ?></td>
        <td><?= $prod -> id_producto ?></td>
        <td><?= $prod -> tipo ?></td>
        <td><?= $prod -> talle ?></td>
        <td><span>$</span><?= $prod ->precio ?> </td>
        <td><a href='detalle/{$prod -> id_producto}' type='button'>Detalles</a></td>
        <td><a href='delete/{$prod -> id_producto}' type='button'>Borrar</a></td> 
        <td><a href='edit/{$prod -> id_producto}' type='button'>Editar</a></td> 
      </tr>
    <?php endforeach; ?>
    </tbody>
</table>

<?php require('formAddProducto.phtml') ?>